### PR TITLE
Added russian localization for ST v.2221 and v.3126

### PR DESCRIPTION
**Pull request by Ant0sh**
Hello, my name is Anton.
Thanks for the menu localization package in Sublima Text.

I added localization in russian language. I ask you to add it to your package LocalizedMenu. I am sure to many people it is useful and they will be grateful.

If you have any questions, I'm ready to respond.

Thank you. I wish you success.

### CODE REVIEW

**Comment by zam1024t** [comment]
Nice work.
I am pleased to receive your pull request!
Could you please solve the above issue in comment?

**Comment by Ant0sh** [comment]
Thank you
which problem? I do not see.

**Comment by zam1024t** [comment]
In README.md line 14.
The link target is wrong.

**Comment by Ant0sh** [comment]
fix
And when you update the package for Sublime Text?

**Comment by zam1024t** [comment]
After testing pass on win/linux/os x for version 2221/3126.
I will merge and release as soon as possible.

**Comment by Ant0sh** [comment]
ok, thanks

please, add word "russian" in description for package in window 'install package'

**Pull request merged**
