### PR TITLE
French language for menu (build 3143) 

### PR DESCRIPTION
**Pull request by fxbenard**
SublimeText3 now speaks French fluently!

Any chance to localize the "LocalizedMenu" settings?

Merry Christmas

### CODE REVIEW

**Comment by zam1024t** [comment]
Merry Christmas! 

I am pleased to receive your pull request with a screenshot, it intuitively show how it works like. Thanks for your impressive mind.

1. Runtime files `.firstRun`/`.lastRun` should not be submit into repository.

Please remove them from pull request, then i can make test on your pull request before merge.

**Comment by fxbenard** [comment]
Done.

**Comment by zam1024t** [comment]
`Localized Menu.sublime-commands` also do not need. It will auto genrate from `.command.json`.

**Comment by fxbenard** [comment]
Done ;)

**Comment by zam1024t** [comment]
`Main.sublime-menu` also do not need. I should told to you above.

**Comment by fxbenard** [comment]
Done maybe

**Comment by zam1024t** [comment]
Thanks for your nice work!

**Pull request merged**
