### PR TITLE
Spanish Translation - Traducción al Español

### PR DESCRIPTION
**Pull request by ChrisTVH**
This is a Spanish translation that I made from scratch, I made it today because I had nothing better to do.

I am a little sad because it did not allow me to translate the whole program, more specifically the complete main menu.
I understand that there will be limitations, but I also know that I could be within the limits of what can be done.

In short, there are some parts in English when you navigate between options and menus. I just translated all the places where it said “caption” I haven't tested if I can add my own, but I know there are some that don't exist for several options.

Here is a picture of what it looks like.

image

### CODE REVIEW

**Review by zam1024t — COMMENTED** [review]
Thanks for your nice work!
1. Your can translate the whole menus, if there is no caption in the node, extraly add one.
2. The major common menus should be shared, this can reduce our transalte work for the next version.
3. There is no changes between build 4166 menus and build 4169 menus. 

Please do the followings to improve this pull request
1. Move these menus to major common folder `menu/4/es_ES`.
```
4169/es_ES/Console Input Widget Context.sublime-menu.json
4169/es_ES/Context.sublime-menu.json
4169/es_ES/Encoding.sublime-menu.json
4169/es_ES/Find in Files.sublime-menu.json
4169/es_ES/Indentation.sublime-menu.json
4169/es_ES/Line Endings.sublime-menu.json
4169/es_ES/Side Bar Mount Point.sublime-menu.json
4169/es_ES/Side Bar.sublime-menu.json
4169/es_ES/Syntax.sublime-menu.json
4169/es_ES/Tab Context.sublime-menu.json
4169/es_ES/Tab Sidebar Context.sublime-menu.json
4169/es_ES/Widget Context.sublime-menu.json
```
2. Delete the shared english menus.
	Easy way to do this, empty `4169/en/*` then copy `4166/en/*` to `4169/en/*`
3. Improve translate missing caption nodes
eg:
https://github.com/zam1024t/LocalizedMenu/blob/v1.8.1/menu/4166/en/Main.sublime-menu.json#L165
https://github.com/zam1024t/LocalizedMenu/blob/v1.8.1/menu/4166/zh_CN/Main.sublime-menu.json#L165

**Comment by zam1024t** [comment]
The old version es_ES translate file.
https://github.com/zam1024t/LocalizedMenu/blob/v1.8.1/menu/3143/es_ES/Main.sublime-menu.json

**Comment by ChrisTVH** [comment]
I have already added all the missing nodes I could find and made a translation, as well as a grammar and language correction to the previous translation.

I can say that the quality is much better now.
I also did what you told me in the previous comment.

These are the things I could not translate because I could not find their node.
sshot-001
sshot-002
sshot-003
sshot-004
sshot-005
sshot-006

**Comment by zam1024t** [comment]
Please remove the duplicate file in the pull request:

- Main menu can not be share, it always different in other version
```
menu/4/es_ES/Main.sublime-menu.json
```

- Shared menus should keep in major common folder

```
menu/4169/es_ES/Console Input Widget Context.sublime-menu.json
menu/4169/es_ES/Context.sublime-menu.json
menu/4169/es_ES/Find in Files.sublime-menu.json
menu/4169/es_ES/Indentation.sublime-menu.json
menu/4169/es_ES/Line Endings.sublime-menu.json
menu/4169/es_ES/Side Bar Mount Point.sublime-menu.json
menu/4169/es_ES/Syntax.sublime-menu.json
menu/4169/es_ES/Widget Context.sublime-menu.json
```

**Comment by zam1024t** [comment]
If you want show in the contributors list, please add links in the all README.md files.
eg:
https://github.com/zam1024t/LocalizedMenu/blob/v1.8.1/README.md?plain=1#L91
https://github.com/zam1024t/LocalizedMenu/blob/v1.8.1/readme/README.zh_CN.md?plain=1#L94
Thanks for you work.

**Comment by zam1024t** [comment]
> These are the things I could not translate because I could not find their node.

We can only ranslate the menu files,  can do nothing with the dynamic menus.

**Comment by ChrisTVH** [comment]
Everything should be ready by now.

**Comment by zam1024t** [comment]
- Is there some reason for use `es` instead of `es_ES`, if not please use es_ES only.
- In  contributors list, keep in one line, join with &, like this:
https://github.com/zam1024t/LocalizedMenu/blob/master/README.md?plain=1#L91

**Comment by ChrisTVH** [comment]
What happens is that this is used for the Español España, and I speak neutral Spanish, several words vary with respect to that, like in Spain they say sangría to indentación.

**Comment by zam1024t** [comment]
chrome://settings/languages

The flowing es locales I found in chrome languages:
```
es
es_AR
es_CL
es_CO
es_CR
es_ES
es_HN
es_MX
es_PE
es_US
es_UY
es_VE
```
So, the neutral Spanish should be the first one.

- Please insert `es` before `es_ES` in contributors list.
- Keep pretty indent in `es_ES` line in all README.md files.
	`es_ES Español*by` to `es_ES Español *by`

**Comment by ChrisTVH** [comment]
Ready.

**Pull request merged**
